"""All VibePlan activities — source of truth for the backend."""

ACTIVITIES: list[dict] = [
    # ── Original 20 ────────────────────────────────────────────────────────
    {
        "id": "sunset-snack-run", "title": "Sunset Snack Run",
        "summary": "Grab cheap snacks and go watch the sunset somewhere nearby.",
        "vibes": ["chill"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Chill friend groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Works best when the sky is clear."}],
        "planningNotes": "Pick a park, overlook, or open field ahead of time.",
    },
    {
        "id": "random-playlist-drive", "title": "Random Playlist Drive",
        "summary": "Set a shared playlist, pick a random direction, and just drive.",
        "vibes": ["random-adventure", "chill"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "1\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Small groups with a driver", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [{"type": "needs-ride", "reason": "Requires at least one driver with a car."}],
        "planningNotes": "Agree on a gas split if the drive goes long.",
    },
    {
        "id": "park-picnic", "title": "Park Picnic",
        "summary": "Pack food from home and chill at a local park.",
        "vibes": ["chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20134 hours", "distanceType": "nearby",
        "bestFor": "Any size group", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Best on a dry, mild day."}],
        "planningNotes": "Each person brings one food item to keep costs low.",
    },
    {
        "id": "thrift-outfit-challenge", "title": "Thrift Store Outfit Challenge",
        "summary": "Each person has $10 and 30 minutes to build the wildest or best outfit.",
        "vibes": ["creative", "social", "random-adventure"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "2\u20133 hours", "distanceType": "nearby",
        "bestFor": "Creative, competitive groups", "effortLevel": "medium", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Find a Goodwill or local thrift store. Agree on budget cap before you go.",
    },
    {
        "id": "photo-scavenger-hunt", "title": "DIY Photo Scavenger Hunt",
        "summary": "Make a list of things to photograph around town and race to complete it.",
        "vibes": ["random-adventure", "active", "creative"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "2\u20133 hours", "distanceType": "nearby",
        "bestFor": "Energetic groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "needs-ride", "reason": "Covering more ground is easier with a car."}],
        "planningNotes": "Write 15\u201320 prompts in advance or use a random generator.",
    },
    {
        "id": "coffee-card-game", "title": "Coffee Shop Card Game Night",
        "summary": "Head to a coffee shop with a deck of cards or a travel board game.",
        "vibes": ["chill", "social"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "2\u20133 hours", "distanceType": "nearby",
        "bestFor": "Small groups", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Check that the coffee shop stays open late enough.",
    },
    {
        "id": "mini-golf", "title": "Mini Golf",
        "summary": "Classic, low-stakes competitive fun for any group size.",
        "vibes": ["active", "social", "random-adventure"], "estimatedCostMin": 8, "estimatedCostMax": 20,
        "timeNeeded": "1\u20132 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "planning-needed", "reason": "Some courses require reservations on weekends."}],
        "planningNotes": "Look up hours and pricing before heading out.",
    },
    {
        "id": "bowling", "title": "Bowling",
        "summary": "Rent shoes, pick a lane, and see who actually has the best form.",
        "vibes": ["active", "social"], "estimatedCostMin": 15, "estimatedCostMax": 30,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Any group size", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "cost-risk", "reason": "Shoe rentals and extra games add up fast."}],
        "planningNotes": "Ask about group pricing or cosmic bowling nights.",
    },
    {
        "id": "late-night-dessert-run", "title": "Late-Night Dessert Run",
        "summary": "Find the best ice cream, donuts, or dessert spot open late.",
        "vibes": ["chill", "social", "random-adventure"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [
            {"type": "late-night", "reason": "Best planned when everyone can stay out past 10 PM."},
            {"type": "needs-ride", "reason": "Easier with a driver to hop between spots."},
        ],
        "planningNotes": "Look up which dessert places are open past 10 PM.",
    },
    {
        "id": "lake-pool-day", "title": "Lake or Pool Day",
        "summary": "Pack towels, snacks, and sunscreen for a full afternoon at the water.",
        "vibes": ["active", "chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 20,
        "timeNeeded": "3\u20136 hours", "distanceType": "short-drive",
        "bestFor": "Larger groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "weather-risk", "reason": "Avoid if storms are forecasted."},
            {"type": "needs-ride", "reason": "Lakes usually require a car to reach."},
        ],
        "planningNotes": "Check if the lake or pool has an entry fee.",
    },
    {
        "id": "outdoor-movie-night", "title": "Outdoor Movie Night",
        "summary": "Set up a projector or drive to an outdoor cinema. Blankets required.",
        "vibes": ["chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 25,
        "timeNeeded": "3\u20134 hours", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "weather-risk", "reason": "Rain or wind will ruin the setup."},
            {"type": "planning-needed", "reason": "Requires projector, extension cord, or finding a drive-in."},
        ],
        "planningNotes": "Vote on the movie in the group chat before showing up.",
    },
    {
        "id": "board-game-cafe", "title": "Board Game Cafe",
        "summary": "Pay a flat fee to play from hundreds of board games while ordering food.",
        "vibes": ["social", "chill", "creative"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "2\u20134 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "planning-needed", "reason": "Popular spots fill up fast; call ahead."}],
        "planningNotes": "Some cafes charge per person per hour; check the pricing model.",
    },
    {
        "id": "farmers-market-challenge", "title": "Farmers Market Challenge",
        "summary": "Each person gets $5 to buy the most interesting snack at the market.",
        "vibes": ["random-adventure", "creative", "social"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Small groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "planning-needed", "reason": "Markets are usually only on weekend mornings."}],
        "planningNotes": "Check local market hours online before going.",
    },
    {
        "id": "content-creation-walk", "title": "Content Creation Walk",
        "summary": "Walk around a cool area and make videos, reels, or a group photo dump.",
        "vibes": ["creative", "social", "random-adventure"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "1\u20133 hours", "distanceType": "nearby",
        "bestFor": "Creative groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [],
        "planningNotes": "Pick a neighborhood, park, or mural wall with good visuals.",
    },
    {
        "id": "mall-challenge", "title": "Mall Challenge",
        "summary": "Set a timer and a small budget for each person to find the weirdest item in the mall.",
        "vibes": ["random-adventure", "social", "creative"], "estimatedCostMin": 0, "estimatedCostMax": 20,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Competitive groups", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "cost-risk", "reason": "Easy to overspend if the challenge budget is not set clearly."}],
        "planningNotes": "Set a strict spending cap before entering.",
    },
    {
        "id": "picnic-and-painting", "title": "Picnic and Painting",
        "summary": "Bring a canvas and cheap paints to a park and paint what you see.",
        "vibes": ["creative", "chill"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "2\u20134 hours", "distanceType": "nearby",
        "bestFor": "Chill creative groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Wind and rain will ruin the canvases."}],
        "planningNotes": "Dollar stores often carry cheap acrylic paint sets and canvases.",
    },
    {
        "id": "park-sports", "title": "Sports at a Park",
        "summary": "Bring a frisbee, football, or volleyball and challenge each other.",
        "vibes": ["active", "social"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "1\u20133 hours", "distanceType": "nearby",
        "bestFor": "Active groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Avoid playing in direct midday heat; go evening instead."}],
        "planningNotes": "Bring water and sunscreen.",
    },
    {
        "id": "bookstore-roulette", "title": "Bookstore Roulette",
        "summary": "Each person picks a random book for someone else to buy and read a page from.",
        "vibes": ["random-adventure", "creative", "chill"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Small curious groups", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Used bookstores keep the cost low.",
    },
    {
        "id": "ice-cream-crawl", "title": "Ice Cream Crawl",
        "summary": "Visit 2\u20133 different ice cream or dessert spots and rate each one.",
        "vibes": ["social", "random-adventure", "chill"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [
            {"type": "needs-ride", "reason": "Moving between multiple spots requires a car."},
            {"type": "cost-risk", "reason": "Multiple stops add up if you are not watching spend."},
        ],
        "planningNotes": "Map out 2\u20133 spots in advance to plan the route.",
    },
    {
        "id": "sunrise-breakfast", "title": "Sunrise Breakfast Challenge",
        "summary": "Wake up before sunrise, make breakfast together, and watch the sun rise.",
        "vibes": ["random-adventure", "chill", "creative"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "2\u20133 hours", "distanceType": "nearby",
        "bestFor": "Adventurous early risers", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "late-night", "reason": "Requires waking up very early (4\u20135 AM in summer)."},
            {"type": "weather-risk", "reason": "Clouds or rain will block the sunrise."},
        ],
        "planningNotes": "Find a hilltop, rooftop, or open field with an eastern view.",
    },
    # ── Batch 2 (added) ─────────────────────────────────────────────────────
    {
        "id": "escape-room", "title": "Escape Room",
        "summary": "Work together under pressure to solve puzzles and escape before the clock runs out.",
        "vibes": ["active", "social", "random-adventure"], "estimatedCostMin": 20, "estimatedCostMax": 35,
        "timeNeeded": "1\u20132 hours", "distanceType": "short-drive",
        "bestFor": "Competitive friend groups", "effortLevel": "medium", "indoorOutdoor": "indoor",
        "warnings": [
            {"type": "planning-needed", "reason": "Booking ahead is required \u2014 walk-ins are rarely available."},
            {"type": "cost-risk", "reason": "Per-person cost adds up quickly for larger groups."},
        ],
        "planningNotes": "Book online at least a day in advance. Groups of 4\u20136 work best.",
    },
    {
        "id": "karaoke-night", "title": "Karaoke Night",
        "summary": "Belt out your favorite songs in a private room or at an open-mic karaoke bar.",
        "vibes": ["social", "random-adventure", "creative"], "estimatedCostMin": 10, "estimatedCostMax": 30,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Loud, fun groups", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [
            {"type": "late-night", "reason": "Most karaoke spots peak after 9 PM."},
            {"type": "cost-risk", "reason": "Private room rentals charge by the hour \u2014 set a time limit."},
        ],
        "planningNotes": "Private room karaoke is worth it for groups of 4+; check for weeknight specials.",
    },
    {
        "id": "food-truck-hop", "title": "Food Truck Hop",
        "summary": "Find a food truck park or spot with multiple trucks and try something from each one.",
        "vibes": ["social", "random-adventure", "chill"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "1\u20132 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "planning-needed", "reason": "Food truck schedules change \u2014 check Instagram or their site first."},
            {"type": "weather-risk", "reason": "Outdoor food truck parks are miserable in rain."},
        ],
        "planningNotes": "Look up a local food truck park or check city food truck trackers.",
    },
    {
        "id": "bike-ride", "title": "Bike Ride Exploration",
        "summary": "Grab bikes and ride a trail, greenway, or neighborhood you've never explored.",
        "vibes": ["active", "random-adventure", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 15,
        "timeNeeded": "1\u20133 hours", "distanceType": "nearby",
        "bestFor": "Active groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "weather-risk", "reason": "Avoid riding in heat above 95\u00b0F \u2014 go early morning or evening."},
            {"type": "needs-ride", "reason": "Getting bikes to a trailhead may require a car or bike rack."},
        ],
        "planningNotes": "Check if there are bike rentals nearby if not everyone has one.",
    },
    {
        "id": "stargazing", "title": "Stargazing Night",
        "summary": "Drive somewhere dark, lay out blankets, and watch the stars with snacks and music.",
        "vibes": ["chill", "random-adventure", "creative"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Chill friend groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "late-night", "reason": "Stars are best after 10 PM when the sky is fully dark."},
            {"type": "weather-risk", "reason": "Clouds completely ruin stargazing \u2014 check the forecast."},
            {"type": "needs-ride", "reason": "Requires driving away from city light pollution."},
        ],
        "planningNotes": "Use a light pollution map to find dark spots nearby. Bring bug spray.",
    },
    {
        "id": "cooking-challenge", "title": "DIY Cooking Challenge",
        "summary": "Pick a mystery ingredient, split into teams, and cook the best dish in 30 minutes.",
        "vibes": ["creative", "social", "random-adventure"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Creative groups at someone's place", "effortLevel": "medium", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Decide on rules and a mystery ingredient at the grocery store before you start.",
    },
    {
        "id": "arcade", "title": "Arcade or Barcade",
        "summary": "Spend a few hours on classic arcade games, claw machines, and skee-ball.",
        "vibes": ["active", "social", "random-adventure"], "estimatedCostMin": 10, "estimatedCostMax": 30,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "cost-risk", "reason": "Game credits go fast \u2014 set a token budget before you start."}],
        "planningNotes": "Look for an all-you-can-play flat rate if available.",
    },
    {
        "id": "rollerskating", "title": "Roller Skating or Rollerblading",
        "summary": "Hit a skate rink or find a smooth path outside for old-school rolling fun.",
        "vibes": ["active", "social", "random-adventure"], "estimatedCostMin": 8, "estimatedCostMax": 20,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "medium", "indoorOutdoor": "both",
        "warnings": [{"type": "planning-needed", "reason": "Indoor rinks often have session times \u2014 check the schedule."}],
        "planningNotes": "Indoor rinks rent skates. For outdoor, bring your own or borrow.",
    },
    {
        "id": "pickleball", "title": "Pickleball or Tennis",
        "summary": "Most parks have free courts \u2014 grab rackets and challenge each other.",
        "vibes": ["active", "social"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Active groups of 2\u20134", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Avoid playing midday in summer \u2014 courts are brutal in the heat."}],
        "planningNotes": "Public courts are usually free. Bring water and sunscreen.",
    },
    {
        "id": "go-karts", "title": "Go-Karts",
        "summary": "Race each other at a local go-kart track \u2014 trash talk fully encouraged.",
        "vibes": ["active", "random-adventure", "social"], "estimatedCostMin": 15, "estimatedCostMax": 40,
        "timeNeeded": "1\u20132 hours", "distanceType": "short-drive",
        "bestFor": "Competitive groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "cost-risk", "reason": "Multiple race sessions add up \u2014 agree on how many rounds before you go."},
            {"type": "planning-needed", "reason": "Some tracks have age or height requirements."},
        ],
        "planningNotes": "Look for combo deals that include multiple laps.",
    },
    {
        "id": "night-market", "title": "Night Market or Street Fair",
        "summary": "Wander a local night market, pop-up fair, or outdoor festival and take it all in.",
        "vibes": ["social", "random-adventure", "creative"], "estimatedCostMin": 5, "estimatedCostMax": 30,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "planning-needed", "reason": "Markets and fairs are event-based \u2014 check local listings first."},
            {"type": "weather-risk", "reason": "Outdoor events get cancelled or miserable in bad weather."},
        ],
        "planningNotes": "Check Eventbrite, Instagram, or local Facebook groups for nearby events.",
    },
    {
        "id": "tie-dye-day", "title": "Tie-Dye Day",
        "summary": "Grab cheap white shirts and a tie-dye kit and go full arts and crafts outside.",
        "vibes": ["creative", "social", "chill"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Creative groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Do this outside \u2014 dye stains everything indoors."}],
        "planningNotes": "Tie-dye kits and white shirts are cheap at craft stores or Amazon.",
    },
    {
        "id": "trivia-night", "title": "Trivia Night",
        "summary": "Find a local bar or restaurant hosting trivia and compete as a team.",
        "vibes": ["social", "chill", "active"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Groups of 4\u20138", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [
            {"type": "planning-needed", "reason": "Trivia nights run on a fixed weekly schedule \u2014 check the day."},
            {"type": "late-night", "reason": "Most trivia events start at 7\u20139 PM."},
        ],
        "planningNotes": "Look up 'trivia night near me' \u2014 many restaurants host weekly free trivia.",
    },
    {
        "id": "hiking", "title": "Hiking or Nature Trail",
        "summary": "Pick a trail, pack snacks, and explore somewhere new on foot.",
        "vibes": ["active", "random-adventure", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20135 hours", "distanceType": "short-drive",
        "bestFor": "Active groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "weather-risk", "reason": "Avoid hiking in extreme heat \u2014 go early morning in summer."},
            {"type": "needs-ride", "reason": "Most trailheads require a car to reach."},
            {"type": "planning-needed", "reason": "Check trail conditions and bring enough water."},
        ],
        "planningNotes": "AllTrails app is great for finding nearby trails by difficulty.",
    },
    {
        "id": "diy-photoshoot", "title": "DIY Friend Photoshoot",
        "summary": "Pick a cool location \u2014 mural, rooftop, field \u2014 and take styled group photos.",
        "vibes": ["creative", "social", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Creative groups", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [],
        "planningNotes": "Golden hour (1 hour before sunset) gives the best lighting for free.",
    },
    {
        "id": "garage-sale-hunt", "title": "Garage Sale Treasure Hunt",
        "summary": "Set a $5 budget each, hit a few garage or estate sales, and find the weirdest item.",
        "vibes": ["random-adventure", "creative", "social"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Adventurous small groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "planning-needed", "reason": "Garage sales are mostly Saturday mornings \u2014 check listings the night before."},
            {"type": "needs-ride", "reason": "Hopping between sales requires a car."},
        ],
        "planningNotes": "Use Facebook Marketplace or Craigslist to map out sales the evening before.",
    },
    {
        "id": "night-swim", "title": "Night Swim",
        "summary": "Sneak in an after-dark swim if someone has a pool \u2014 bring speakers and snacks.",
        "vibes": ["chill", "social", "random-adventure"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Small groups with pool access", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "late-night", "reason": "Best after dark \u2014 requires someone with pool access."},
            {"type": "weather-risk", "reason": "Skip if there's lightning or thunderstorms nearby."},
        ],
        "planningNotes": "Make sure adults know if needed. Keep music reasonable for neighbors.",
    },
    # ── Urban & Exploration ─────────────────────────────────────────────────
    {
        "id": "urban-photography", "title": "Urban Photography Walk",
        "summary": "Pick a part of town you never go to \u2014 murals, alleys, rooftops, weird architecture \u2014 and shoot a photo series.",
        "vibes": ["creative", "random-adventure", "social"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "1\u20133 hours", "distanceType": "nearby",
        "bestFor": "Creative groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [],
        "planningNotes": "Golden hour (1 hr before sunset) is the best free lighting. Scout murals on Google Maps first.",
    },
    {
        "id": "geocaching", "title": "Geocaching",
        "summary": "Use the Geocaching app to hunt for hidden containers scattered around your city. Real-world treasure hunting.",
        "vibes": ["random-adventure", "active", "creative"], "estimatedCostMin": 0, "estimatedCostMax": 0,
        "timeNeeded": "1\u20133 hours", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "needs-ride", "reason": "Some geocaches are far enough to need a car."}],
        "planningNotes": "Download the free Geocaching app. Filter for difficulty 1\u20132 to start.",
    },
    {
        "id": "random-coordinates", "title": "Random Coordinates Challenge",
        "summary": "Generate random GPS coordinates within 30 minutes of you and drive there. No preview, no googling first.",
        "vibes": ["random-adventure", "social"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "2\u20134 hours", "distanceType": "short-drive",
        "bestFor": "Adventurous groups", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [
            {"type": "needs-ride", "reason": "Requires a driver and car."},
            {"type": "far-drive", "reason": "Coordinates could land anywhere \u2014 set a max radius first."},
        ],
        "planningNotes": "Use a random GPS coordinate generator website. Set a 20\u201330 min drive radius.",
    },
    {
        "id": "highest-point", "title": "Find the Highest Point in Your City",
        "summary": "Research, navigate to, and conquer the highest natural or structural point you can legally access near you.",
        "vibes": ["random-adventure", "active"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20134 hours", "distanceType": "short-drive",
        "bestFor": "Adventurous duos or small groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "needs-ride", "reason": "Likely requires a car to reach the trailhead or access point."},
            {"type": "planning-needed", "reason": "Check access rules \u2014 some peaks or rooftops require permission."},
        ],
        "planningNotes": "Search '[your city] highest point' or use topographic maps.",
    },
    {
        "id": "street-chalk-art", "title": "Street Chalk Art Mural",
        "summary": "Claim a section of sidewalk and create a massive collaborative chalk mural \u2014 no skill required.",
        "vibes": ["creative", "social", "chill"], "estimatedCostMin": 3, "estimatedCostMax": 8,
        "timeNeeded": "1\u20132 hours", "distanceType": "walking",
        "bestFor": "Creative groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Rain wipes it out instantly \u2014 do this on a dry day."}],
        "planningNotes": "Big sidewalk chalk packs are cheap at dollar stores. Find a busy corner for an audience.",
    },
    # ── Outdoor / Nature ────────────────────────────────────────────────────
    {
        "id": "disc-golf", "title": "Disc Golf",
        "summary": "Most cities have free disc golf courses in parks. Grab a few frisbees and play 9\u201318 holes.",
        "vibes": ["active", "social", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "1\u20133 hours", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Best on a clear, non-windy day \u2014 wind ruins disc accuracy."}],
        "planningNotes": "Search 'disc golf near me' \u2014 most are free. You can share discs to start.",
    },
    {
        "id": "hammock-day", "title": "Hammock Day in the Park",
        "summary": "String up hammocks between trees, put on a playlist, bring snacks, and do absolutely nothing productive.",
        "vibes": ["chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20134 hours", "distanceType": "nearby",
        "bestFor": "Chill groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Pointless if it rains or is too hot. Go during golden hour."}],
        "planningNotes": "Basic hammocks are $15\u201320 online and last forever.",
    },
    {
        "id": "campfire-night", "title": "Backyard Campfire Night",
        "summary": "Build a fire, make s'mores, tell stories, and stay outside until it's way too late.",
        "vibes": ["chill", "social", "random-adventure"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "3\u20135 hours", "distanceType": "walking",
        "bestFor": "Any size group", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "late-night", "reason": "This naturally turns into a late night \u2014 plan accordingly."},
            {"type": "weather-risk", "reason": "Wind and rain make fires impossible and miserable."},
            {"type": "planning-needed", "reason": "Need a fire-safe spot \u2014 backyard, fire pit, or permitted area."},
        ],
        "planningNotes": "Grab firewood from a gas station. Marshmallows, chocolate, and graham crackers cost under $10.",
    },
    {
        "id": "kayaking", "title": "Kayaking or Canoeing",
        "summary": "Rent kayaks or canoes for an hour and explore a lake, river, or bay at your own pace.",
        "vibes": ["active", "random-adventure", "chill"], "estimatedCostMin": 15, "estimatedCostMax": 40,
        "timeNeeded": "2\u20134 hours", "distanceType": "short-drive",
        "bestFor": "Active groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "weather-risk", "reason": "Skip if storms are possible \u2014 lightning on water is dangerous."},
            {"type": "needs-ride", "reason": "Rental spots are usually at a specific waterfront location."},
            {"type": "planning-needed", "reason": "Check rental availability \u2014 busy summer days book up."},
        ],
        "planningNotes": "Look for city or state park paddle rentals \u2014 usually cheaper than private operators.",
    },
    {
        "id": "swimming-hole", "title": "Swimming Hole or Creek Adventure",
        "summary": "Find a local swimming hole, creek, or natural pool and spend the afternoon in the water.",
        "vibes": ["active", "random-adventure", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "3\u20135 hours", "distanceType": "short-drive",
        "bestFor": "Active groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "needs-ride", "reason": "Swimming holes are usually outside city limits."},
            {"type": "weather-risk", "reason": "Check for recent rainfall \u2014 creeks flood fast after storms."},
            {"type": "planning-needed", "reason": "Research access and water safety before going."},
        ],
        "planningNotes": "Search '[your city] swimming holes' or ask locals. Bring water shoes.",
    },
    {
        "id": "paddleboarding", "title": "Stand-Up Paddleboarding",
        "summary": "Rent SUP boards and attempt to stay on them. Falling in is half the fun.",
        "vibes": ["active", "random-adventure", "social"], "estimatedCostMin": 20, "estimatedCostMax": 40,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Active groups", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "weather-risk", "reason": "Choppy water from wind makes balancing very hard."},
            {"type": "needs-ride", "reason": "Board rental locations are at specific waterfronts."},
        ],
        "planningNotes": "Wear sunscreen everywhere \u2014 reflection off the water is intense.",
    },
    {
        "id": "overnight-camping", "title": "Overnight Car Camping",
        "summary": "Pack sleeping bags, find a nearby campsite, stay a night, and wake up outside.",
        "vibes": ["random-adventure", "chill", "social"], "estimatedCostMin": 10, "estimatedCostMax": 30,
        "timeNeeded": "12\u201316 hours", "distanceType": "short-drive",
        "bestFor": "Groups of 2\u20136", "effortLevel": "high", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "planning-needed", "reason": "Campsites need to be reserved \u2014 often weeks in advance."},
            {"type": "needs-ride", "reason": "Requires a car to haul gear to the campsite."},
            {"type": "weather-risk", "reason": "Check the forecast \u2014 sleeping in rain with no tent experience is miserable."},
        ],
        "planningNotes": "ReserveAmerica or Recreation.gov for bookings. Car camping is beginner-friendly.",
    },
    # ── Games & Competition ─────────────────────────────────────────────────
    {
        "id": "laser-tag", "title": "Laser Tag",
        "summary": "Run through a dark arena and hunt each other down with laser guns. No skill required, full chaos.",
        "vibes": ["active", "social", "random-adventure"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "1\u20132 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "cost-risk", "reason": "Multiple sessions add up \u2014 set a round limit before you pay."}],
        "planningNotes": "Most laser tag arenas offer multi-game packages. Weekday afternoons are less crowded.",
    },
    {
        "id": "axe-throwing", "title": "Axe Throwing",
        "summary": "Rent a lane, get coached for 10 minutes, then compete to see who hits the bullseye.",
        "vibes": ["active", "random-adventure", "social"], "estimatedCostMin": 20, "estimatedCostMax": 35,
        "timeNeeded": "1\u20132 hours", "distanceType": "short-drive",
        "bestFor": "Competitive groups of 2\u20138", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [
            {"type": "planning-needed", "reason": "Most venues require a reservation, especially on weekends."},
            {"type": "cost-risk", "reason": "Lane rental is per-hour \u2014 groups of 4+ split the cost best."},
        ],
        "planningNotes": "Closed-toe shoes required. Most venues are 18+ but some allow 16+ with a waiver.",
    },
    {
        "id": "board-game-home", "title": "Board Game Night at Home",
        "summary": "Pull out every board game in the house and play until someone flips the table.",
        "vibes": ["social", "chill", "creative"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "3\u20135 hours", "distanceType": "walking",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Catan, Ticket to Ride, Codenames, and Wavelength are all crowd favorites. Order pizza.",
    },
    {
        "id": "card-tournament", "title": "Card Game Tournament",
        "summary": "Set up brackets for Uno, Phase 10, BS, or any card game and crown a champion.",
        "vibes": ["social", "random-adventure", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "2\u20134 hours", "distanceType": "walking",
        "bestFor": "Groups of 4\u201310", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Write the bracket on a whiteboard or paper. Loser makes snack runs.",
    },
    {
        "id": "video-game-tournament", "title": "Video Game Tournament",
        "summary": "Set up brackets on any multiplayer game and run a real tournament with rounds.",
        "vibes": ["active", "social", "random-adventure"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "3\u20135 hours", "distanceType": "walking",
        "bestFor": "Any group at someone's house", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Mario Kart, Smash Bros, Rocket League, or FIFA work great for tournaments. Make a bracket.",
    },
    {
        "id": "puzzle-race", "title": "Puzzle Race",
        "summary": "Buy two identical puzzles, split into teams, and race to finish first.",
        "vibes": ["social", "active", "creative"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "2\u20134 hours", "distanceType": "walking",
        "bestFor": "Competitive groups of 4+", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "500-piece puzzles are a good challenge level. Dollar stores sometimes carry them cheap.",
    },
    {
        "id": "vending-machine-roulette", "title": "Vending Machine Roulette",
        "summary": "Everyone puts in $2, presses a random button without looking, and eats whatever comes out.",
        "vibes": ["random-adventure", "social", "chill"], "estimatedCostMin": 2, "estimatedCostMax": 8,
        "timeNeeded": "30 min\u20131 hour", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Best done late night when the activity just needs a quick laugh.",
    },
    # ── Creative & DIY ──────────────────────────────────────────────────────
    {
        "id": "pottery-class", "title": "Pottery or Ceramics Studio",
        "summary": "Walk in for a drop-in wheel-throwing or hand-building session at a local studio.",
        "vibes": ["creative", "chill", "social"], "estimatedCostMin": 20, "estimatedCostMax": 45,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Creative groups of 2\u20136", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "planning-needed", "reason": "Most studios require booking drop-in sessions in advance."}],
        "planningNotes": "Look for 'paint your own pottery' studios too \u2014 lower skill floor, same fun.",
    },
    {
        "id": "candle-making", "title": "DIY Candle Making",
        "summary": "Buy a cheap candle kit and spend an afternoon making custom-scented candles at someone's place.",
        "vibes": ["creative", "chill", "social"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Small creative groups", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Candle-making kits from Amazon or craft stores include everything.",
    },
    {
        "id": "vision-board-party", "title": "Vision Board Party",
        "summary": "Everyone brings magazines and makes a collage vision board for the summer or the year.",
        "vibes": ["creative", "chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Small groups", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Grab old magazines from doctors' offices or thrift stores. Poster boards are $1 each.",
    },
    {
        "id": "film-photography", "title": "Film Camera Day",
        "summary": "Grab a cheap disposable camera or dust off an old film camera and shoot a full roll in one day.",
        "vibes": ["creative", "chill", "random-adventure"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "2\u20134 hours", "distanceType": "nearby",
        "bestFor": "Creative groups or pairs", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [],
        "planningNotes": "Disposable cameras are $12\u201318 at CVS/Walgreens. One-hour developing is a vibe.",
    },
    {
        "id": "friendship-bracelets", "title": "Friendship Bracelet Station",
        "summary": "Set up strings, beads, and patterns and spend an afternoon making bracelets for each other.",
        "vibes": ["creative", "chill", "social"], "estimatedCostMin": 5, "estimatedCostMax": 15,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [],
        "planningNotes": "Embroidery floss is cheap. Look up beginner knotting patterns on YouTube before you start.",
    },
    {
        "id": "short-film", "title": "Film a Short Comedy Sketch",
        "summary": "Write a dumb 3-minute sketch, cast yourselves, film it on a phone, and edit it together.",
        "vibes": ["creative", "social", "random-adventure"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "3\u20135 hours", "distanceType": "walking",
        "bestFor": "Creative groups of 3\u20136", "effortLevel": "high", "indoorOutdoor": "both",
        "warnings": [],
        "planningNotes": "CapCut is free and easy for editing. Keep the script under 2 minutes.",
    },
    {
        "id": "time-capsule", "title": "Summer Time Capsule",
        "summary": "Fill a box with notes, photos, and small items from right now and hide it to open later.",
        "vibes": ["creative", "chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "1\u20132 hours", "distanceType": "walking",
        "bestFor": "Close friend groups", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [],
        "planningNotes": "Use a waterproof container if burying it. Set a calendar reminder to open it together.",
    },
    # ── Food & Culinary ─────────────────────────────────────────────────────
    {
        "id": "boba-crawl", "title": "Boba Tea Crawl",
        "summary": "Hit every boba or bubble tea spot in your area and score each one on taste, value, and vibes.",
        "vibes": ["social", "random-adventure", "chill"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [
            {"type": "needs-ride", "reason": "Hopping between multiple spots needs a car."},
            {"type": "cost-risk", "reason": "Boba drinks are $5\u20138 each \u2014 each stop adds up."},
        ],
        "planningNotes": "Make a scorecard with categories: taste, toppings, aesthetics, price.",
    },
    {
        "id": "late-night-diner", "title": "Late-Night Diner Run",
        "summary": "Roll into a 24-hour diner at midnight, order weird things off the menu, stay for two hours.",
        "vibes": ["random-adventure", "social", "chill"], "estimatedCostMin": 8, "estimatedCostMax": 20,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "late-night", "reason": "This is literally a late-night activity. Plan for midnight or later."}],
        "planningNotes": "Google '24-hour diner near me.' Order the most chaotic item on the menu.",
    },
    {
        "id": "international-snack-haul", "title": "International Snack Haul",
        "summary": "Hit an Asian grocery, international market, or H-Mart and spend $10 each on weird snacks to try.",
        "vibes": ["random-adventure", "social", "creative"], "estimatedCostMin": 8, "estimatedCostMax": 15,
        "timeNeeded": "1\u20132 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Rate each snack out of 10. Japanese, Korean, and Mexican sections have the most interesting stuff.",
    },
    {
        "id": "backyard-bbq", "title": "Backyard BBQ",
        "summary": "Fire up the grill, everyone brings one ingredient, and you spend the afternoon eating outside.",
        "vibes": ["social", "chill"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "3\u20135 hours", "distanceType": "walking",
        "bestFor": "Any size group", "effortLevel": "medium", "indoorOutdoor": "outdoor",
        "warnings": [
            {"type": "weather-risk", "reason": "Wind and rain make grilling difficult and unpleasant."},
            {"type": "planning-needed", "reason": "Requires access to a grill and outdoor space."},
        ],
        "planningNotes": "Each person brings one item \u2014 burgers, hot dogs, chips, drinks, a side.",
    },
    {
        "id": "taco-crawl", "title": "Taco Crawl",
        "summary": "Map out 3\u20134 taco spots, eat one or two tacos at each, and rank them at the end.",
        "vibes": ["social", "random-adventure", "chill"], "estimatedCostMin": 10, "estimatedCostMax": 25,
        "timeNeeded": "2\u20133 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "both",
        "warnings": [{"type": "needs-ride", "reason": "Multiple stops require a car."}],
        "planningNotes": "Research spots in advance. Food trucks often have the best tacos.",
    },
    {
        "id": "cooking-show-night", "title": "Chopped-Style Cooking Night",
        "summary": "Everyone picks one mystery ingredient from the fridge, then everyone cooks something using all mystery items.",
        "vibes": ["creative", "social", "random-adventure"], "estimatedCostMin": 10, "estimatedCostMax": 20,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Groups at someone's house with a kitchen", "effortLevel": "medium", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "One person plays host/judge. Timer set for 30 minutes. Judging: taste, creativity, presentation.",
    },
    # ── Music & Performance ─────────────────────────────────────────────────
    {
        "id": "open-mic", "title": "Open Mic Night",
        "summary": "Find a local coffee shop or venue hosting open mic and watch strangers (or go up yourself).",
        "vibes": ["social", "chill", "creative"], "estimatedCostMin": 0, "estimatedCostMax": 15,
        "timeNeeded": "2\u20133 hours", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "late-night", "reason": "Open mics usually run 7\u201310 PM at the earliest."}],
        "planningNotes": "If anyone has a song or poem, sign up to perform. Even watching is a great time.",
    },
    {
        "id": "free-concert", "title": "Free Concert in the Park",
        "summary": "Most cities run free outdoor concerts in summer \u2014 pack snacks, bring a blanket, show up.",
        "vibes": ["chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20134 hours", "distanceType": "nearby",
        "bestFor": "Any size group", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "weather-risk", "reason": "Outdoor concerts get cancelled for storms."}],
        "planningNotes": "Search '[your city] free outdoor concerts summer 2026' or check your city's parks department.",
    },
    {
        "id": "music-video-shoot", "title": "Music Video Shoot",
        "summary": "Pick a song, divide roles (director, cast, camera), and film a full lip-sync music video.",
        "vibes": ["creative", "social", "random-adventure"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "3\u20134 hours", "distanceType": "nearby",
        "bestFor": "Creative groups of 3\u20136", "effortLevel": "high", "indoorOutdoor": "both",
        "warnings": [],
        "planningNotes": "Plan a shot list first. Pick a song under 3 minutes. CapCut or iMovie for editing.",
    },
    {
        "id": "backyard-jam", "title": "Backyard Jam Session",
        "summary": "Anyone who plays anything \u2014 guitar, drums, keys, even a tambourine \u2014 gets together and jams.",
        "vibes": ["creative", "social", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 10,
        "timeNeeded": "2\u20134 hours", "distanceType": "walking",
        "bestFor": "Musically inclined groups", "effortLevel": "low", "indoorOutdoor": "outdoor",
        "warnings": [{"type": "late-night", "reason": "Outdoor music at night may upset neighbors."}],
        "planningNotes": "Non-musicians can clap, sing, or run a playlist between songs. Bring snacks.",
    },
    # ── Chill / Relaxed ─────────────────────────────────────────────────────
    {
        "id": "movie-marathon", "title": "Themed Movie Marathon",
        "summary": "Pick a director, actor, franchise, or vibe and watch 3 movies back-to-back with themed snacks.",
        "vibes": ["chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 15,
        "timeNeeded": "5\u20138 hours", "distanceType": "walking",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "late-night", "reason": "3 movies means this ends at midnight or later."}],
        "planningNotes": "Vote on the theme beforehand. Assign each person a snack that matches a movie.",
    },
    {
        "id": "spa-day", "title": "DIY Spa Day",
        "summary": "Face masks, nail painting, foot soaks, candles, and good music. Zero cost, all vibes.",
        "vibes": ["chill", "social", "creative"], "estimatedCostMin": 0, "estimatedCostMax": 15,
        "timeNeeded": "2\u20134 hours", "distanceType": "walking",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Sheet face masks are $1 each at Asian beauty stores or Amazon. Pick a playlist in advance.",
    },
    {
        "id": "fort-building", "title": "Epic Indoor Fort Build",
        "summary": "Claim the living room, use every blanket and pillow in the house, and build the biggest fort possible.",
        "vibes": ["creative", "chill", "social"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "2\u20134 hours", "distanceType": "walking",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Clip lights inside for ambiance. Watch a movie inside it once it's built.",
    },
    {
        "id": "all-nighter", "title": "Planned All-Nighter",
        "summary": "Everyone sleeps over, no one sleeps. Games, food, movies, and chaos until the sun comes up.",
        "vibes": ["random-adventure", "social", "chill"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "8\u201312 hours", "distanceType": "walking",
        "bestFor": "Close friend groups of 3\u20138", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "late-night", "reason": "This is the whole point. Make sure everyone's parents know."}],
        "planningNotes": "Plan activity rotations: games 10\u201312, movie 12\u20132, food run 2\u20133, chaos 3\u2013sunrise.",
    },
    # ── Community & Volunteering ────────────────────────────────────────────
    {
        "id": "volunteer-day", "title": "Volunteer Day",
        "summary": "Spend a few hours at a food bank, community garden, or neighborhood cleanup as a group.",
        "vibes": ["active", "social"], "estimatedCostMin": 0, "estimatedCostMax": 0,
        "timeNeeded": "3\u20135 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "medium", "indoorOutdoor": "both",
        "warnings": [{"type": "planning-needed", "reason": "Most volunteer orgs require signup at least a few days ahead."}],
        "planningNotes": "VolunteerMatch.org or your city's parks department list open opportunities.",
    },
    {
        "id": "dog-shelter", "title": "Dog Shelter Volunteer Day",
        "summary": "Sign up to walk, socialize, or clean at a local dog or cat shelter for a few hours.",
        "vibes": ["active", "social", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 0,
        "timeNeeded": "2\u20134 hours", "distanceType": "short-drive",
        "bestFor": "Any group", "effortLevel": "medium", "indoorOutdoor": "both",
        "warnings": [{"type": "planning-needed", "reason": "Shelters require advance signup and sometimes a short orientation."}],
        "planningNotes": "Call or email the shelter at least a week ahead. Some require volunteers to be 16+.",
    },
    {
        "id": "clothing-swap", "title": "Clothing Swap Party",
        "summary": "Everyone brings 5\u201310 items they don't wear anymore and swaps for new-to-you pieces.",
        "vibes": ["creative", "social", "chill"], "estimatedCostMin": 0, "estimatedCostMax": 5,
        "timeNeeded": "2\u20133 hours", "distanceType": "walking",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [],
        "planningNotes": "Set a rule: everything must be clean and wearable. Leftovers go to a thrift donation.",
    },
    # ── Yes Day / Random Challenges ─────────────────────────────────────────
    {
        "id": "yes-day", "title": "Yes Day Challenge",
        "summary": "For 2 hours, one person proposes activities and everyone has to say yes to the first 5 suggestions.",
        "vibes": ["random-adventure", "social", "active"], "estimatedCostMin": 5, "estimatedCostMax": 20,
        "timeNeeded": "2\u20134 hours", "distanceType": "nearby",
        "bestFor": "Adventurous friend groups", "effortLevel": "medium", "indoorOutdoor": "both",
        "warnings": [{"type": "cost-risk", "reason": "Suggestions could cost money \u2014 agree on a per-activity cap."}],
        "planningNotes": "Rotate who suggests. Nothing dangerous, illegal, or over an agreed budget.",
    },
    {
        "id": "random-restaurant", "title": "Spin the Wheel Restaurant Run",
        "summary": "List every restaurant within 15 minutes, spin a wheel to pick one randomly, and go immediately.",
        "vibes": ["random-adventure", "social"], "estimatedCostMin": 10, "estimatedCostMax": 30,
        "timeNeeded": "1\u20132 hours", "distanceType": "nearby",
        "bestFor": "Any group", "effortLevel": "low", "indoorOutdoor": "indoor",
        "warnings": [{"type": "cost-risk", "reason": "Wheel could land on a pricier spot \u2014 set a max price per person."}],
        "planningNotes": "Use Wheelofnames.com. Add 10+ options. No vetoing the result.",
    },
]
